CREATE DATABASE M1S07_EX8

CREATE TABLE FUNCIONARIOS
(
	ID INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(15) NOT NULL,
	CARGO VARCHAR(10),

)

ALTER TABLE FUNCIONARIOS DROP COLUMN TEL1
ALTER TABLE FUNCIONARIOS DROP COLUMN TEL2
ALTER TABLE FUNCIONARIOS DROP COLUMN CARGO



SELECT * FROM FUNCIONARIOS

INSERT INTO FUNCIONARIOS (ID, NOME, CARGO, TEL1, TEL2) VALUES(1, 'Marcos', 'Atendente', 3654589, 36545987),
															 (2, 'Maria', 'Gerente', 3654698, 36524569);
INSERT INTO FUNCIONARIOS VALUES (3, 'Julia', 'Atendente', 3654962, 12365458)

-- 1 FORMA DE NORMALIZAÇÃO (1NF)

CREATE TABLE TELEFONES
(
	ID_FUNCIONARIO INT NOT NULL,
	TELEFONE VARCHAR(15),
	PRIMARY KEY (ID_FUNCIONARIO, TELEFONE),
	FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID)
)

SELECT * FROM TELEFONES

INSERT INTO TELEFONES (ID_FUNCIONARIO, TELEFONE) VALUES
	(1, 3654589), 
	(1, 36545987),
	(2, 3654698), 
	(2, 36524569),
	(3, 3654962), 
	(3, 12365458)

-- 3 FORMA DE NORMALIZAÇÃO (3NF)

CREATE TABLE CARGOS
(
	ID INT PRIMARY KEY,
	NOME_CARGO VARCHAR(15)
)

ALTER TABLE FUNCIONARIOS ADD ID_CARGO INT
ALTER TABLE FUNCIONARIOS ADD FOREIGN KEY (ID_CARGO) REFERENCES CARGOS(ID)

INSERT INTO CARGOS (ID, NOME_CARGO) VALUES
	(1, 'Atendende'),
	(2, 'Gerente'),
	(3, 'Atendente')

SELECT * FROM CARGOS C

-- QUANDO SE USA FROM FUNCIONARIO AS F A TABELA FUNCIONARIO PASSA A SER CHAMADA DE F NO NESTE BLOCO DE CÓDIGO
UPDATE F
SET F.ID_CARGO = CARGOS.ID
FROM FUNCIONARIOS AS F
INNER JOIN CARGOS ON F.CARGO = CARGOS.NOME_CARGO;

