CREATE DATABASE M1S07_EX1_7

-- EXERCICIO 01
CREATE TABLE CLIENTE
(
ID INT NOT NULL,
NOME VARCHAR(20) NOT NULL,
TELEFONE VARCHAR(10),
ENDEREÇO VARCHAR(20) NOT NULL,
)

-- EXERCICIO 02

INSERT INTO CLIENTE (ID, NOME, TELEFONE, ENDEREÇO) VALUES (1,'Vinicius Silva', 987664, 'Rua Girassol'),
														  (2, 'Maria Antonia', 12456, 'Rua Rosas');
INSERT INTO CLIENTE VALUES (3, 'Marcus Vinicius', 654123, 'Rua Itajai')

-- EXERCICIO 03

SELECT * FROM CLIENTE

-- EXERCICIO 04

SELECT ID FROM CLIENTE

-- EXERCICIO 05

SELECT * FROM CLIENTE
WHERE NOME like '%u%'

-- EXERCICIO 06

UPDATE CLIENTE
SET ENDEREÇO = 'Rua do Limão'
WHERE ID = 3

-- EXERCICIO 07

DELETE CLIENTE
WHERE ID = 2